service: ton

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  listarModelosDisponiveis:
    handler: src/functions/listarModelosDisponiveis/handler.listarModelosDisponiveis
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-offline
